dict_don = {'ð': 'ơ̆', 'ẽ': 'ĕ', '¡': 'i', 'mĩ': 'mĭ', 'ợ': 'ơ', 'ồ': 'ŏ', 'ố': 'ơ̆', 'ỗ': 'ô̆', 'ơi': 'ơĭ', 'ổi': 'ôĭ', 'š': 'ĕ', 'Š': 'ê̆', 'ủ': 'ŭ', 'Ủ': 'Ŭ', 'ũ': 'ŭ', 'Ũ': 'Ŭ'}

radioContentMap = {
        'pôlok': 'pơlĕi',
        'pôloêk': 'pơlĕi',
        'pôtaêm': 'pơtăm',
        'uê': 'ŭ',
        'huyeân': 'huên',
        'Huyeân': 'Huên',
        'Huyeân': 'Huên',
        'tröêk': 'trưk',
        'adring': 'adrĭng',
        'ñe hôyoh': 'đe hơyoh',
        'Ñôêng roêng': 'Đưng rŏng',
        'ñôêng roêng': 'đưng rŏng',
        'xaõ': 'sa',
        'aõit': 'axit',
        'tơpalh': 'tơblah',
        'eÊâ': 'ê̆',
        'ø': '',
        'aï': 'a',
        'eã': 'ê',
        'uõ': 'ŭ',
        'uù': 'u',
        'oei': 'uĕi',
        'ôi': 'ơĭ',
        'ôêi': 'ơĭ',
        'ÔÊi': 'Ơĭ',
        'Ôêi': 'Ơĭ',
        'aê': 'ă',
        'ôê': 'ơ̆',
        'ñ': 'đ',
        'Ñ': 'Đ',
        'Uê': 'Ŭ',
        'ei': 'ĕi',
        'eêi': 'ĕi',
        'oê': 'ŏ',
        'iê': 'ĭ',
        'eâ': 'ê',
        'eä': 'ê',
        'ô': 'ơ',
        'Ô': 'Ơ',
        'oâ': 'ô',
        'öê': 'ư',
        'eê': 'ê',
        'ö': 'ư',
        'aâ': 'â',
        # 'i': 'ĭ',
    }

contentSpecialMap = {
        'đi đăng': 'đĭ đăng',
        'Bi thư': 'Bĭ thư',
        'bi thư': 'bĭ thư',
        'trŭng': 'jrŭ',
        'đuoÊâi': 'đuôĭ',
        # 'đuôÊi': 'đuôĭ',
        # 'kruôÊi': 'kruôĭ',
        'ôÊih': 'ôih',
        'ôÊi ': 'uôĭ ',
        'kruôi': 'kruôĭ',
        'đuôi': 'đuôĭ',
        'oêng': 'weng',
        'oeng': 'weng',
        'ksôÊ': 'ksô',
        'caùch mang': 'cach mang',
        'chpuôih': 'chơpuih',
        'd/c': 'đ/c',
        'ji ': 'jĭ ',
        'ji,': 'jĭ,',
        'ji': 'jĭ',
        'kjung': 'kơjung',
        'adrêÊch': 'adrêch',
        'bôÊ': 'bŏ',
        'xa': 'sa',
        'Xa': 'Sa',
        'jêÊ': 'jê̆',
        'ksoÊâ': 'ksô',
        'alêÊ': 'alê̆',
        'amnê': 'amrĕ',
        'ngam': 'ngam',
        'cuû caûi': 'bum cai',
        'lyê': 'ly',
        'AÙN1': 'ANS1',
        'hoù,': 'hoa,',
        'ù': '',
        'Sơùnư': 'Sơn',
        'yok': 'yŏk',
        'Bơghê': 'Bơgê',
        'bơghê': 'bơgê',
        'Nghò': 'Nghi',
        'kuyet': 'kuyêt',
        'nghi quyêt': 'nghi kuyêt',
        'truy quyet': 'truy quet',
        'Quyêt': 'Kuyêt',
        'quêt': 'quet',
        'nnghê': 'nghê',
        'Năr': 'Năr',
    }

contentMap = {
        'liêt sit': 'liet si',
        'đi đăng': 'đĭ đăng',
        'Điê đăng': 'Đĭ đăng',
        'điê đăng': 'đĭ đăng',
        'điê ': 'đĭ ',
        'điêê': 'đĭ',
        'ơêi': 'ơĭ',
        'ơê': 'ơ̆',
        'ƠÊi': 'Ơĭ',
        'ơi': ' ơĭ',
        'Ơi': 'Ơĭ',
        'chiênh': 'chĭnh',
        'Adriêng': 'Adrĭng',
        'adriêng': 'adrĭng',
        'kiêa': 'kĭa',
        'jiê': 'jĭ',
        'biê ': 'bĭ ',
        'eê': 'ĕ',
        'eÊâ': 'ê̆',
        'êÊ': 'ê̆',
        'EÊ': 'Ĕ',
        'uê': 'ŭ',
        'UÊ': 'Ŭ',
        'ưê': 'ư̆',
        'oÊâ': 'ô̆',
        ' yoêk': ' yŏk',
        'oê': 'ŏ',
        'ôê': 'ô̆',
        'ôÊ': 'ô̆',
        'ÁN1': 'ANS1',
        'oeng': 'weng',
        'ôÊih': 'ôih',
        'uôÊi ': 'uôĭ ',
        'kruôi': 'kruôĭ',
        'đuôi': 'đuôĭ',
        'bone': 'bơne',
        'Dơno': 'Dơnŏ',
        'dơno': 'dơnŏ',
        'dơ no': 'dơnŏ',
        'Dơ no': 'Dơ nŏ',
        'nghiê ': 'nghĭ ',
        # 'ksôÊ': 'ksô̆',
        'Ahrei': 'Ahrĕi',
        'tổng': 'tông',
        'tơdrogn': 'tơdrong',
        'Nghị': 'Nghi',
        'Việt': 'Viêt',
        'kơdriêng': 'kơdrĭng',
        'nôngnghiêp': 'nông nghiêp',
        'miê': 'mĭ',
        'jởẳ': 'jơh',
        'ahrei': 'ahrĕi',
        'kruô̆i': 'kruôĭ',
        'alê ': 'alê̆ ',
        'Alê ': 'Alê̆ ',
        'đuô̆i': 'đuôĭ',
        'xã': 'xa',
        'huyện': 'huyên'
    }
    
